config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :graphics

  root to: 'graphics#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def hello
        render html:"Hello, Vikash"
    end
end

app/controllers/graphics_controller.rb
class GraphicsController < ApplicationController
    def index
        @result, @count = top_trending, search.count
        return unless params[:search]
        @result, @count = giphy_search(params[:search]), search.count
      end
    
      def top_trending
        response = HTTParty.get("http://api.giphy.com/v1/gifs/trending?api_key=#{GIPHY_KEY}&limit=9")
        response['data']
      end
    
      def giphy_search(query)
        response = HTTParty.get("http://api.giphy.com/v1/gifs/search?api_key=#{GIPHY_KEY}&limit=9&q=#{query}")
        search.update!(count: (search.count + 1))
        return response['data']
      end
    
      def search
        Search.first
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graphics_helper.rb
module GraphicsHelper
    def display_helper(result)
        count = 1
        str = ""
        result.each do |gif|
          if count == 1
            str << "<tr><td><img src = #{gif['images']['fixed_height_downsampled']['url']} ></td>"
          else
            str << "<td><img src = #{gif['images']['fixed_height_downsampled']['url']} ></td>"
          end
          if count == 3
            count = 0
            str << "</tr>"
          end
          count = count +1
        end
        str
      end
end

app/views/graphics/index.html.erb
<a href = '/'><h1> Graphics Interchange Format (GIF) </h1> </a>
<%= form_tag(graphics_path, method: 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search' %> No. of Searches <%= @count %>
<% end %>

</br>
</br>
</br>

<table>
    <%= display_helper(@result).html_safe %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>